name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/wyvox/action-setup-pnpm
      - uses: wyvox/action-setup-pnpm@v3
        with: { node-version: 24 }

      - name: lint
        run: pnpm run lint
